---
title: "Forecasting with TSRVFL"
author: "Your Name"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Forecasting with TSRVFL}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7,
  fig.height = 5
)
```

# Introduction

The `tsrvflf` function combines model fitting and forecasting in one convenient step. This vignette demonstrates how to use this function for time series forecasting with RVFL networks.

## Basic Usage

Let's start with a simple example using simulated data that contains both trend and seasonal components:

```{r basic_example}
library(rvfl)
library(forecast)  # for ts functions

plot(rvfl::tsrvflf(USAccDeaths, h = 3L, lags = 3L, 
            engine = stats::lm, 
            n_hidden_features = 5, 
            nodes_sim = "sobol", 
            activ = "relu"))
```


```{r basic_example2}
plot(rvfl::tsrvflf(USAccDeaths, h = 20, lags = 20, 
            engine = stats::lm, 
            n_hidden_features = 5, 
            nodes_sim = "sobol", 
            activ = "relu"))
```
